### ISSUE TITLE
./mib2zabbix.pl: No such file or directory

### ISSUE THREAD

**Issue by natalysheinin** [cavaliercoder/mib2zabbix#10]
I am runing this command:
`./mib2zabbix.pl -o MY_FILE.my`

2 comments, when I run the same script without the .pl extension it gets further than this error by giving me an error already brought up here (about the circular arrays).
Secondly, does this program accept .my files?

**Comment by cavaliercoder** [comment]
The script doesn't actually read MIB or `.my` files itself. It relies on the OID tree built by the SNMP library. So if your `.my` file is correctly loaded by snmp, it will be available to mib2zabbix. To ensure your `.my` file is loaded correctly, please see http://net-snmp.sourceforge.net/tutorial/tutorial-5/commands/mib-options.html.

The `-o` flag is intended to define the OID in the loaded tree (like `.x.y.z.1.2.3`), from which a template will be generated; not the MIB/My file you wish to import.

This is mainly because an OID tree can be defined in multiple, interdependent files. It's best to let the SNMP lib handle dependency resolution and consume its tree.
